--- #YAML:1.0
name:               CGI-Lingua
version:            0.44
abstract:           Create a multilingual web page
author:
    - Nigel Horne <njh@bandsman.co.uk>
license:            GPL
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    CGI::Info:            0
    Class::Load:          0
    Data::Validate::IP:   0
    HTTP::BrowserDetect:  0
    I18N::AcceptLanguage:  0
    I18N::LangTags::Detect:  0
    Locale::Language:     0
    Locale::Object::Country:  0
    Net::Whois::IANA:     0
    Net::Whois::IP:       0
    Sys::Syslog:          0
    Test::More:           0
    Test::NoWarnings:     0
    Test::Requires:       0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
